export const LOGIN = "LOGIN";
export const LOGIN_SUCCEED = "LOGIN_SUCCEED";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_WORKSPACES = "GET_WORKSPACES";
export const GET_WORKSPACES_SUCCEED = "GET_WORKSPACES_SUCCEED";
export const GET_WORKSPACES_FAILED = "GET_WORKSPACES_FAILED";

export const ADD_WORKSPACE = "ADD_WORKSPACE";
export const ADD_WORKSPACE_SUCCEED = "ADD_WORKSPACE_SUCCEED";
export const ADD_WORKSPACE_FAILED = "ADD_WORKSPACE_FAILED";

export const UPDATE_WORKSPACE = "UPDATE_WORKSPACE";
export const UPDATE_WORKSPACE_SUCCEED = "UPDATE_WORKSPACE_SUCCEED";
export const UPDATE_WORKSPACE_FAILED = "UPDATE_WORKSPACE_FAILED";

export const DELETE_WORKSPACE = "DELETE_WORKSPACE";
export const DELETE_WORKSPACE_SUCCEED = "DELETE_WORKSPACE_SUCCEED";
export const DELETE_WORKSPACE_FAILED = "DELETE_WORKSPACE_FAILED";

export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECTS_SUCCEED = "GET_PROJECTS_SUCCEED";
export const GET_PROJECTS_FAILED = "GET_PROJECTS_FAILED";
